name: oficinaescolar_colaboradores
description: "Oficina Escolar Colaboradores"
publish_to: 'none'

version: 1.0.0+01

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.5.0
  curved_navigation_bar: ^1.0.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  http: ^1.4.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  flutter_html: ^3.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  open_filex: ^4.7.0
  dio: ^5.8.0+1
  provider: ^6.1.5
  image_picker: ^1.1.2
  sqflite: ^2.4.2
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_app_badge: ^2.0.2
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  auto_size_text: ^3.0.0
  flutter_html_table: ^3.0.0
  font_awesome_flutter: ^10.9.0  
  syncfusion_flutter_pdfviewer: ^31.1.18
  qr_flutter: ^4.1.0
  

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/oficinasiglas.png
    - assets/images/logo_escuela.jpg
    - assets/images/user.png
    - assets/icons/logowhats.png
    - assets/icons/oficinaescolarpapas.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/oficinaescolarcolaboradores.jpeg"
