// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMB1fPsacFXOmvIkgF9q2fxAEjgm50HL4',
    appId: '1:424263278007:web:ab6f8571ed8b0100b61c32',
    messagingSenderId: '424263278007',
    projectId: 'oficinaescolar-colaboradores',
    authDomain: 'oficinaescolar-colaboradores.firebaseapp.com',
    storageBucket: 'oficinaescolar-colaboradores.firebasestorage.app',
    measurementId: 'G-6XPGRHNWP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlFKwwlyX7Evo-YvQCPlH7Vk5Rn0AM-tk',
    appId: '1:424263278007:android:38a7184b09db8fabb61c32',
    messagingSenderId: '424263278007',
    projectId: 'oficinaescolar-colaboradores',
    storageBucket: 'oficinaescolar-colaboradores.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADycfAUzUaC31h4OIHOaSy8AyNiT_Dh58',
    appId: '1:424263278007:ios:7c7dab89c62d40f3b61c32',
    messagingSenderId: '424263278007',
    projectId: 'oficinaescolar-colaboradores',
    storageBucket: 'oficinaescolar-colaboradores.firebasestorage.app',
    iosBundleId: 'com.edgargutierrez.oficinaescolarColaboradores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADycfAUzUaC31h4OIHOaSy8AyNiT_Dh58',
    appId: '1:424263278007:ios:aa6dc05cf1a50445b61c32',
    messagingSenderId: '424263278007',
    projectId: 'oficinaescolar-colaboradores',
    storageBucket: 'oficinaescolar-colaboradores.firebasestorage.app',
    iosBundleId: 'com.example.oficinaescolarColaboradores',
  );
}
